name: dotnet_release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore simple-ffmpeg-app.sln

    - name: Build solution
      run: msbuild simple-ffmpeg-app.sln -t:rebuild -property:Configuration=Release

    - name: Get previous tag name
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.1

    - name: Create new tag name
      id: getNewTag
      run: |
        echo Previous: ${{ steps.previoustag.outputs.tag }}
        echo New: $(echo ${{ steps.previoustag.outputs.tag }} | awk -F. -v OFS=. '{$NF += 1; print'})
        echo "TagName=$(echo ${{ steps.previoustag.outputs.tag }} | awk -F. -v OFS=. '{$NF += 1; print'})" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get release notes
      run: |
        cat D:\\a\\ffmpeg-app\\ffmpeg-app\\simple-ffmpeg-app\\notes\\release_notes\\current.txt >> D:\\a\\ffmpeg-app\\ffmpeg-app\\simple-ffmpeg-app\\notes\\release_notes\\release_notes.md
    - name: Show release notes
      run: cat D:\\a\\ffmpeg-app\\ffmpeg-app\\simple-ffmpeg-app\\notes\\release_notes\\release_notes.md
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.getNewTag.outputs.TagName }}
        prerelease: true
        body: Release build version ${{ steps.getNewTag.outputs.TagName }}
        body_path: D:/a/ffmpeg-app/ffmpeg-app/simple-ffmpeg-app/notes/release_notes/release_notes.md
        fail_on_unmatched_files: true
        target_commitish: "main"
        generate_release_notes: true
        files: "D:/a/ffmpeg-app/ffmpeg-app/simple-ffmpeg-app/bin/Release/simple-ffmpeg-app.exe"
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      env:
        GITHUB_REPOSITORY: gfriesen98/ffmpeg-app
