name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore simple-ffmpeg-app.sln

    - name: Build solution
      run: msbuild simple-ffmpeg-app.sln -t:rebuild -property:Configuration=Release

    #- name: testing
    #  run: echo asdasdasd > release.txt
    - name: Get Previous Tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: v0.0.1

    - name: Set New Tag Version
      run: echo ${{ steps.previoustag.outputs.tag }} | awk -F. -v OFS=. '{$NF += 1; print}'
      
    - name: Create Tag Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.0.2.1
        prerelease: true
        body: Autogenerated build release
        fail_on_unmatched_files: true
        target_commitish: "main"
        generate_release_notes: true
        #files: simple-ffmpeg-app.exe
        #files: ".\\simple-ffmpeg-app\\bin\\Release\\simple-ffmpeg-app.exe"
        #files: release.txt
        files: "D:/a/ffmpeg-app/ffmpeg-app/simple-ffmpeg-app/bin/Release/simple-ffmpeg-app.exe"
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      env:
        GITHUB_REPOSITORY: gfriesen98/ffmpeg-app
